name: Python test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install package
        run: |
          python -m pip install -r requirements.txt
          python -m pip install .
      - name: Test with pytest
        run: pytest .

      - name: Build docs
        run: |
          cd docs && make html
