name: Python test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mypackage
          environment-file: environment.yml
          auto-activate-base: false
      - run: |
          conda info
          conda list
      - name: Install package
        run: |
          python3 -m pip install .
      - name: Test with pytest
        run: pytest .

      - name: Build docs
        run: |
          cd docs && make html

      - name: Archive build artifacts (i.e. documentation)
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: |
            docs/build


